INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (3, 'Tuyên', 'Hoàng', '0123456789', 'hoangtuyen@hotmail.com', 'tuyenhoang', 'tuyenhoang', '2020-06-20 16:18:22.000000', '2020-06-20 16:18:24.000000', 2, 1, 'https://c8.alamy.com/comp/JBDWRK/smiling-young-geek-guy-adjusting-his-bow-tie-JBDWRK.jpg', '<p>Nhân vật Cù Trọng Xoay từng do Đinh Tiến Dũng thủ vai. Đinh Tiến Dũng sinh <a href="/wiki/5_th%C3%A1ng_10" title="5 tháng 10">5 tháng 10</a><sup class="noprint Inline-Template Template-Fact" style="white-space:nowrap;">[<i><a href="/wiki/Wikipedia:Ch%C3%BA_th%C3%ADch_ngu%E1%BB%93n_g%E1%BB%91c" title="Wikipedia:Chú thích nguồn gốc"><span title="Tuyên bố này cần tham khảo đến các nguồn đáng tin cậy.">cần dẫn nguồn</span></a></i>]</sup> năm 1981<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup><sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup><sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup>) tại <a href="/wiki/H%C3%A0_Nam_Ninh" title="Hà Nam Ninh">Hà Nam Ninh</a> (nay là <a href="/wiki/Nam_%C4%90%E1%BB%8Bnh" title="Nam Định">Nam Định</a>). Thời sinh viên, anh từng theo học và tốt nghiệp Khóa 44 ngành Cây trồng trường <a href="/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_N%C3%B4ng_nghi%E1%BB%87p_H%C3%A0_N%E1%BB%99i" class="mw-redirect" title="Trường Đại học Nông nghiệp Hà Nội">Trường Đại học Nông nghiệp Hà Nội</a>, tại đây anh đã từng trải qua các chức vụ như Chủ tịch Hội sinh viên khoa Nông học, Chủ tịch Hội sinh viên trường <a href="/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_N%C3%B4ng_nghi%E1%BB%87p_H%C3%A0_N%E1%BB%99i" class="mw-redirect" title="Trường Đại học Nông nghiệp Hà Nội">Trường Đại học Nông nghiệp Hà Nội</a>.<sup id="cite_ref-htv_4-0" class="reference"><a href="#cite_note-htv-4">[4]</a></sup> Sau khi tốt nghiệp, anh đi theo ngành công tác thanh niên, công tác tại Trung ương đoàn.<sup id="cite_ref-htv_4-1" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Sau khi rời Trung ương Đoàn, anh về làm tại <a href="/wiki/%C4%90%E1%BA%A1i_h%E1%BB%8Dc_FPT" class="mw-redirect" title="Đại học FPT">Đại học FPT</a> trong vai trò trưởng phòng Công tác sinh viên. Hiện nay anh giữ vị trí Trưởng ban văn hóa của Công ty FPT.<sup id="cite_ref-htv_4-2" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Anh tham gia soạn kịch bản của chương trình <i>Thư giãn cuối tuần</i>, <i><a href="/wiki/G%E1%BA%B7p_nhau_cu%E1%BB%91i_tu%E1%BA%A7n" title="Gặp nhau cuối tuần">Gặp nhau cuối tuần</a></i>, <i><a href="/wiki/G%E1%BA%B7p_nhau_cu%E1%BB%91i_n%C4%83m" title="Gặp nhau cuối năm">Gặp nhau cuối năm</a></i> của <a href="/wiki/%C4%90%C3%A0i_Truy%E1%BB%81n_h%C3%ACnh_Vi%E1%BB%87t_Nam" title="Đài Truyền hình Việt Nam">Đài Truyền hình Việt Nam</a> và nổi tiếng từ khi làm chuyên mục <i><a href="/w/index.php?title=H%E1%BB%8Fi_Xo%C3%A1y_%C4%91%C3%A1p_Xoay&amp;action=edit&amp;redlink=1" class="new" title="Hỏi Xoáy đáp Xoay (trang chưa được viết)">Hỏi Xoáy đáp Xoay</a></i> của chương trình <i>Thư giãn cuối tuần</i>.<sup id="cite_ref-htv_4-3" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Đinh Tiến Dũng cũng tham gia vào trò chơi truyền hình thực tế <i><a href="/wiki/C%E1%BA%B7p_%C4%91%C3%B4i_ho%C3%A0n_h%E1%BA%A3o_(m%C3%B9a_1)" class="mw-redirect" title="Cặp đôi hoàn hảo (mùa 1)">Cặp đôi hoàn hảo</a></i> của kênh <a href="/wiki/VTV3" title="VTV3">VTV3</a> <a href="/wiki/%C4%90%C3%A0i_Truy%E1%BB%81n_h%C3%ACnh_Vi%E1%BB%87t_Nam" title="Đài Truyền hình Việt Nam">Đài Truyền hình Việt Nam</a>. Anh đã lọt vào top 4 của cuộc thi và nhận được sự ủng hộ của nhiều khán giả.
</p>
<p>Thứ 6 tầng 13: Đến hẹn lại lên, tối thứ 6 hàng tuần, với vai trò là MC dẫn chương trình khá xoay và hóm hỉnh, anh đã tạo được những tiếng cười cho khán giả (chủ yếu là cán bộ nhân viên FPT!). Các khách mời nổi tiếng như NS: Phú Quang, Nguyễn Cường, Lê Minh Sơn... ca sĩ: Ngọc Khuê, Hoàng Quyên, Minh Chuyên... Đêm diễn đọng lại nhiều dư âm cho khán giả.
</p>');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (4, 'Lực', 'Nguyễn', '0365987225', 'lucsy@yahoo.com', 'lucsy', 'lucsy1234', '2020-06-20 16:22:41.000000', '2020-06-20 16:22:42.000000', 2, 1, 'https://image.thanhnien.vn/768/uploaded/huuhau/2016_05_10/screenshot2016-05-10at112627am_njpf.png', '<p>Giờ ta chẳng còn chi<br> Mãi trắng tay mà thôi<br> Đời bạc gian lắm phủ phàng<br> Tiền có kiếm như nước rồi cũng sẽ trôi hết<br> Tay không trắng tay lại vẹn không?</p>
<p>Đời phiêu lưu là thế<br> Không biết đến ngày mai<br> Nên giờ đây mới đắng cay<br> Ngồi trước tấm gương sáng rọi vào đó mới thấy<br> Thân xác hoang tàn không nhận ra.</p>
<p>[ĐK:]<br> Kiếp Đỏ Đen lyrics on ChiaSeNhac.com<br> Ta mang bao tội lỗi nên thân ta giờ đây<br> Kiếp sống không nhà không người thân<br> Ta mang bao tội lỗi<br> Người ơi ta đâu còn chi<br> Xin hãy tránh xa kiếp đỏ đen!</p>');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (2, 'Nam', 'Nguyễn', '0420420420', 'namct@gmail.com', 'namct420', 'namct1234', '2020-06-20 15:48:13.000000', '2020-06-20 15:48:12.000000', 2, 1, 'https://vignette.wikia.nocookie.net/karofipedia/images/d/df/FEELGOODCOMRADE2.jpg/revision/latest/scale-to-width-down/310?cb=20171229175719&path-prefix=vi', '<p>Page được thành lập bởi một nhóc con sinh năm 2004 (katyusha) vì một suy nghĩ non nớt "Meme me daddy đem meme đến Việt Nam nhưng lại để lũ mem làm hỏng nó". Ngày 17/7/2017, page lần đầu tiên thành lập với cái tên "Meme tươi từ rừng Pác Bó" nhưng katyusha không thích cái tên này nên đã nhờ đến Nguyễn Đông (đồng chí của katyusha, sau này trở thành wee🅱lord) để đặt cái tên mới, tên page sau đó đã được dự định đổi thành "Dank Meme dành cho thiếu niên tự kỉ" nhưng chưa bao giờ được đặt vì page bị chặn đổi tên. Chấp nhận cái tên Meme tươi từ rừng Pác Bó, katyusha đã mời đồng chí của mình vào làm chung, người này sau này chính là wee🅱lord.
</p>
<p>Sau đó, page bước vào thời kì phát triển. Sự phát triển lúc này được xem là khó khăn vì các page meme ít chất lượng mọc lên khá nhiều. Nhưng may mắn, các meme đầu của page khá chất lượng nên gây được một ít sự chú ý, và sự chú ý của page được nâng lên khi wee🅱lord đăng một video về Chester Bennington, meme này sau đó được share vào nhiều group nước ngoài nên page gây được sự chú ý đến thêm khá nhiều người. Và đỉnh điểm của sự phát triển này là khi katyusha bắt đầu đăng một meme parody của meme "no vegetal" liên quan đế Cá rô phi và lựu đạn. Meme này nhanh chóng gây được rất nhiều sự chú ý và được share đi nhiều nơi, nhưng hậu quả của meme này là một người đã share vào group Cùng Troll Phản Động vì nghĩ đây là bài viết nói xấu nhà nước, làm page bị report và rate 1 sao. Katyusha phải đóng rating và minh oan cho page vì thiếu lực lượng phản kháng. Sau meme này, page bắt đầu được nhiều người biết đến hơn. Page sau đó đăng meme và phát triển bình thường, đồng thời tuyển thêm admin gồm <a href="/vi/wiki/Inshi" title="Inshi">i n s h i</a>, <a href="/vi/wiki/DXY" title="DXY">DXY</a>, và một số admin từ Meme me daddy và lập group <a class="new" title="Rừng Pác Bó (trang chưa được viết)" rel="nofollow" data-uncrawlable-url="L3ZpL3dpa2kvUiVFMSVCQiVBQm5nX1AlQzMlQTFjX0IlQzMlQjM/YWN0aW9uPWVkaXQmcmVkbGluaz0x">Rừng Pác Bó</a>. Page phát triển đến khi gần cán mốc 9000 like thì sập không lí do, mọi kháng nghị đều không thành công, dẫn đến sự ra đời của Meme tươi từ rừng Pác Bó II
</p>
<p>Sau khi kháng nghị với Facebook không thành công, katyusha lập page Meme tươi từ rừng Pác Bó II. Do đã có nhiều sự chú ý từ Meme tươi từ rừng Pác Bó nên việc khởi đầu khá dễ dàng, 2000 like trong vòng 2 ngày, sau đó tiếp tục phát triển nhờ thường xuyên đăng meme và đôi khi repost các meme cũ. Khi gần cán mốc 8000 like, page nhận được thông tin về việc các page sjw Lipsyncney Flopears, Lộ Lộ Corp,... đang hùa nhau công kích một giáo viên. Nhận được nhiều sự ủng hộ, ngày 3/9/2017 page bắt đầu lên án hành động hùa nhau công kích giáo viên của Lộ Lộ Corp. Lipsyncney Flopears sau đó đã đăng một lời kêu gọi giả trong nhóm của mình, sử dụng thông tin giả "Meme tươi từ rừng Pác Bó kì thị đồng tính" mặc dù page chưa nhắm đến những người đồng tính để tẩy não và kêu gọi các thành viên của mình (mặc dù chưa biết chuyện gì xảy ra) hùa report và rate 1 sao, ngay sau đó, Lộ Lộ Corp cũng tham gia, dẫn đến việc katyusha phải viết một bản tuyên ngôn chính thức chiến tranh. Bản tuyên ngôn này chính thức dẫn đến Chiến Tranh Pác Bó vĩ đại
</p>
<p>Meme tươi từ rừng Pác Bó II lúc đó yếu thế hơn so với các page sjw nên việc chống cự khá khó khăn. Giữa cuộc chiến, Meme tươi từ rừng Pác Bó II sập vì report, Meme tươi từ rừng Pác Bó III ra đời
</p>
<p>Sau khi Meme tươi từ rừng Pác Bó II sập, Meme tươi từ rừng Pác Bó III vẫn tiếp tục chiến tranh với lực lượng mạnh hơn, page đã kêu gọi tấn công ngược lại khiến Lipsyncney Flopears và Lộ Lộ Corp phải sợ hãi khóa page, ngay sau đó Lipsyncney Flopears tuyên bố đầu hàng và đứng ngoài cuộc chiến, bỏ lại Lộ Lộ Corp chiến đấu một mình. Lộ Lộ Corp sau đó cũng tuyên bố đầu hàng và kí hiệp ước Ka-ro-fi để châm dứt chiến tranh
</p>
<p>Chiến thắng thuộc về Meme tươi từ rừng Pác Bó III, sau chiến tranh, sự phát triển của page bắt đầu yếu đi, và cuối cũng page sập khi chỉ mới gần 2.500 like. Và Meme tươi từ rừng Pác Bó IV Damke ra đời và chịu số phận tương tự, cũng giống như Meme tươi từ rừng Pác Bó V và 6.0. Page đang hoạt động hiện tại là Meme tươi từ rừng Pác Bó 7.0
</p>');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (1, 'Đức', 'Nguyễn', '0915971992', 'vanduc1234@gmail.com', 'vanduc2514', 'vanduc1234', '2020-06-20 15:46:14.000000', '2020-06-20 15:47:28.000000', 2, 1, 'https://toomanyhotguys.files.wordpress.com/2018/07/june25brad_web3.jpg?w=764', '<ul><li>"chả là mấy thằng bạn cùng lớp đứa nào cũng có ghệ hết rồi, hôm nọ bọn nó hỏi sao mày to cao dáng chuẩn vậy mà chưa có ghệ chơi? sực nhớ bấy lâu nay vẫn "riêng mình anh cô đơn" nên muốn kiếm con ghệ về xem sao.. dáng thì chuẩn rồi nhưng mặt xấu trai quá, có ai có cách nào giúp mình kiếm ghệ không?"</li><li>"ảnh mình đây, đứa nào cười tao đấm 1 phát chết luôn":</li></ul>');