INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (3, 'Tuyên', 'Hoàng', '0123456789', 'hoangtuyen@hotmail.com', 'tuyenhoang', 'tuyenhoang', '2020-06-20 16:18:22.000000', '2020-06-20 16:18:24.000000', 2, 1, 'https://c8.alamy.com/comp/JBDWRK/smiling-young-geek-guy-adjusting-his-bow-tie-JBDWRK.jpg', '<p>Nhân vật Cù Trọng Xoay từng do Đinh Tiến Dũng thủ vai. Đinh Tiến Dũng sinh <a href="/wiki/5_th%C3%A1ng_10" title="5 tháng 10">5 tháng 10</a><sup class="noprint Inline-Template Template-Fact" style="white-space:nowrap;">[<i><a href="/wiki/Wikipedia:Ch%C3%BA_th%C3%ADch_ngu%E1%BB%93n_g%E1%BB%91c" title="Wikipedia:Chú thích nguồn gốc"><span title="Tuyên bố này cần tham khảo đến các nguồn đáng tin cậy.">cần dẫn nguồn</span></a></i>]</sup> năm 1981<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup><sup id="cite_ref-2" class="reference"><a href="#cite_note-2">[2]</a></sup><sup id="cite_ref-3" class="reference"><a href="#cite_note-3">[3]</a></sup>) tại <a href="/wiki/H%C3%A0_Nam_Ninh" title="Hà Nam Ninh">Hà Nam Ninh</a> (nay là <a href="/wiki/Nam_%C4%90%E1%BB%8Bnh" title="Nam Định">Nam Định</a>). Thời sinh viên, anh từng theo học và tốt nghiệp Khóa 44 ngành Cây trồng trường <a href="/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_N%C3%B4ng_nghi%E1%BB%87p_H%C3%A0_N%E1%BB%99i" class="mw-redirect" title="Trường Đại học Nông nghiệp Hà Nội">Trường Đại học Nông nghiệp Hà Nội</a>, tại đây anh đã từng trải qua các chức vụ như Chủ tịch Hội sinh viên khoa Nông học, Chủ tịch Hội sinh viên trường <a href="/wiki/Tr%C6%B0%E1%BB%9Dng_%C4%90%E1%BA%A1i_h%E1%BB%8Dc_N%C3%B4ng_nghi%E1%BB%87p_H%C3%A0_N%E1%BB%99i" class="mw-redirect" title="Trường Đại học Nông nghiệp Hà Nội">Trường Đại học Nông nghiệp Hà Nội</a>.<sup id="cite_ref-htv_4-0" class="reference"><a href="#cite_note-htv-4">[4]</a></sup> Sau khi tốt nghiệp, anh đi theo ngành công tác thanh niên, công tác tại Trung ương đoàn.<sup id="cite_ref-htv_4-1" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Sau khi rời Trung ương Đoàn, anh về làm tại <a href="/wiki/%C4%90%E1%BA%A1i_h%E1%BB%8Dc_FPT" class="mw-redirect" title="Đại học FPT">Đại học FPT</a> trong vai trò trưởng phòng Công tác sinh viên. Hiện nay anh giữ vị trí Trưởng ban văn hóa của Công ty FPT.<sup id="cite_ref-htv_4-2" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Anh tham gia soạn kịch bản của chương trình <i>Thư giãn cuối tuần</i>, <i><a href="/wiki/G%E1%BA%B7p_nhau_cu%E1%BB%91i_tu%E1%BA%A7n" title="Gặp nhau cuối tuần">Gặp nhau cuối tuần</a></i>, <i><a href="/wiki/G%E1%BA%B7p_nhau_cu%E1%BB%91i_n%C4%83m" title="Gặp nhau cuối năm">Gặp nhau cuối năm</a></i> của <a href="/wiki/%C4%90%C3%A0i_Truy%E1%BB%81n_h%C3%ACnh_Vi%E1%BB%87t_Nam" title="Đài Truyền hình Việt Nam">Đài Truyền hình Việt Nam</a> và nổi tiếng từ khi làm chuyên mục <i><a href="/w/index.php?title=H%E1%BB%8Fi_Xo%C3%A1y_%C4%91%C3%A1p_Xoay&amp;action=edit&amp;redlink=1" class="new" title="Hỏi Xoáy đáp Xoay (trang chưa được viết)">Hỏi Xoáy đáp Xoay</a></i> của chương trình <i>Thư giãn cuối tuần</i>.<sup id="cite_ref-htv_4-3" class="reference"><a href="#cite_note-htv-4">[4]</a></sup>
</p>
<p>Đinh Tiến Dũng cũng tham gia vào trò chơi truyền hình thực tế <i><a href="/wiki/C%E1%BA%B7p_%C4%91%C3%B4i_ho%C3%A0n_h%E1%BA%A3o_(m%C3%B9a_1)" class="mw-redirect" title="Cặp đôi hoàn hảo (mùa 1)">Cặp đôi hoàn hảo</a></i> của kênh <a href="/wiki/VTV3" title="VTV3">VTV3</a> <a href="/wiki/%C4%90%C3%A0i_Truy%E1%BB%81n_h%C3%ACnh_Vi%E1%BB%87t_Nam" title="Đài Truyền hình Việt Nam">Đài Truyền hình Việt Nam</a>. Anh đã lọt vào top 4 của cuộc thi và nhận được sự ủng hộ của nhiều khán giả.
</p>
<p>Thứ 6 tầng 13: Đến hẹn lại lên, tối thứ 6 hàng tuần, với vai trò là MC dẫn chương trình khá xoay và hóm hỉnh, anh đã tạo được những tiếng cười cho khán giả (chủ yếu là cán bộ nhân viên FPT!). Các khách mời nổi tiếng như NS: Phú Quang, Nguyễn Cường, Lê Minh Sơn... ca sĩ: Ngọc Khuê, Hoàng Quyên, Minh Chuyên... Đêm diễn đọng lại nhiều dư âm cho khán giả.
</p>');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (4, 'Lực', 'Nguyễn', '0365987225', 'lucsy@yahoo.com', 'lucsy', 'lucsy1234', '2020-06-20 16:22:41.000000', '2020-06-20 16:22:42.000000', 2, 1, 'https://image.thanhnien.vn/768/uploaded/huuhau/2016_05_10/screenshot2016-05-10at112627am_njpf.png', '<p>Giờ ta chẳng còn chi<br> Mãi trắng tay mà thôi<br> Đời bạc gian lắm phủ phàng<br> Tiền có kiếm như nước rồi cũng sẽ trôi hết<br> Tay không trắng tay lại vẹn không?</p>
<p>Đời phiêu lưu là thế<br> Không biết đến ngày mai<br> Nên giờ đây mới đắng cay<br> Ngồi trước tấm gương sáng rọi vào đó mới thấy<br> Thân xác hoang tàn không nhận ra.</p>
<p>[ĐK:]<br> Kiếp Đỏ Đen lyrics on ChiaSeNhac.com<br> Ta mang bao tội lỗi nên thân ta giờ đây<br> Kiếp sống không nhà không người thân<br> Ta mang bao tội lỗi<br> Người ơi ta đâu còn chi<br> Xin hãy tránh xa kiếp đỏ đen!</p>');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (2, 'Nam', 'Nguyễn', '0420420420', 'namct@gmail.com', 'namct420', 'namct1234', '2020-06-20 15:48:13.000000', '2020-06-20 15:48:12.000000', 2, 1, 'https://vignette.wikia.nocookie.net/karofipedia/images/d/df/FEELGOODCOMRADE2.jpg/revision/latest/scale-to-width-down/310?cb=20171229175719&path-prefix=vi','Đây là nam CT');
INSERT INTO shark_squad.users (id, first_name, last_name, phone, email, username, password, created_date, updated_time, roles_id, status, avatar_link, bio) VALUES (1, 'Đức', 'Nguyễn', '0915971992', 'vanduc1234@gmail.com', 'vanduc2514', 'vanduc1234', '2020-06-20 15:46:14.000000', '2020-06-20 15:47:28.000000', 2, 1, 'https://toomanyhotguys.files.wordpress.com/2018/07/june25brad_web3.jpg?w=764', '<ul><li>"chả là mấy thằng bạn cùng lớp đứa nào cũng có ghệ hết rồi, hôm nọ bọn nó hỏi sao mày to cao dáng chuẩn vậy mà chưa có ghệ chơi? sực nhớ bấy lâu nay vẫn "riêng mình anh cô đơn" nên muốn kiếm con ghệ về xem sao.. dáng thì chuẩn rồi nhưng mặt xấu trai quá, có ai có cách nào giúp mình kiếm ghệ không?"</li><li>"ảnh mình đây, đứa nào cười tao đấm 1 phát chết luôn":</li></ul>');